repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        types_or: [python, jupyter]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black-jupyter
        language_version: python3.11
