site_name: ''
docs_dir: pages

theme:
  name: material
  palette:
    scheme: slate
  icon:
    logo: fontawesome/brands/github
  features:
    - toc.integrate
    - navigation.top
  custom_dir: pages/overrides

extra:
  homepage: https://github.com/MarkCButler/lending-club

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - pages/overrides/.icons

plugins:
  - search
  - git-revision-date-localized
